[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
reputation_oracle = "EDtweyEKbbesS4YbumnbdQeNr3aqdvUF9Df4g9wuuVoj"

[programs.devnet]
reputation_oracle = "EDtweyEKbbesS4YbumnbdQeNr3aqdvUF9Df4g9wuuVoj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/andy/dev-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
